
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipeline-manager
  annotations:
    tekton-pipeline.app: test
secrets:
  - name: harbor-cred
  - name: minio-cred
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-pipeline-manager
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tekton-pipeline.app: test
  name: tekton-pipeline-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-pipeline-manager
subjects:
- kind: ServiceAccount
  name: tekton-pipeline-manager
  namespace: default